title: Site
columns:
	hero:
		width: 1/1
		sections:
			avatar:
				type: files
				max: 1
			hero:
				type: fields
				fields:
					heading:
						type: text
						placeholder: '{{ site.title }}'
					subheading:
						type: text
	pages:
		width: 1/1
		sections:
			pages:
				templates:
					- text
					- modals
					- contact
	footer1:
		width: 1/3
		fields:
			footer_col1_header:
				label: Column 1 Header
				type: text
			footer_col1_text:
				label: Column 1 Text
				type: textarea
	footer2:
		width: 1/3
		fields:
			footer_col2_header:
				label: Column 2 Header
				type: text
			footer_col2_links:
				label: Column 2 Text
				type: structure
				fields:
					icon:
						type: select
						options:
							fa-facebook-f: Facebook
							fa-twitter: Twitter
							fa-linkedin-in: LinkedIn
							fa-dribbble: Dribbble
					url: true
	footer3:
		width: 1/3
		fields:
			footer_col3_header:
				label: Column 3 Header
				type: text
			footer_col3_text:
				label: Column 3 Text
				type: textarea
			